name: build java_dragonwell
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - java-dragonwell/**
      - .github/workflows/java-dragonwell.yml

permissions:
  actions: read
  packages: write

concurrency:
  group: java-dragonwell-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "java_${{ matrix.tag }}_dragonwell_${{ matrix.arch }}"
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    env:
      DOCKER_CLIENT_TIMEOUT: 120
      COMPOSE_HTTP_TIMEOUT: 120
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
        tag:
          - 8
          - 11
          - 17
          - 21
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v6

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v4
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: ./java-dragonwell
          platforms: linux/${{ matrix.arch }}
          file: ./java-dragonwell/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/donpedrotv/pterodactyl-images:java_${{ matrix.tag }}_dragonwell-${{ matrix.arch }}

  merge:
    name: "java_${{ matrix.tag }}_dragonwell"
    if: ${{ always() }}
    needs: build_and_push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: [8, 11, 17, 21]
    steps:
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker buildx imagetools create --tag ghcr.io/donpedrotv/pterodactyl-images:java_${{ matrix.tag }}_dragonwell ghcr.io/donpedrotv/pterodactyl-images:java_${{ matrix.tag }}_dragonwell-amd64 ghcr.io/donpedrotv/pterodactyl-images:java_${{ matrix.tag }}_dragonwell-arm64
